//Entry Form
const END_ADD_ENTRY_PROCESS     = "END_ADD_ENTRY_PROCESS";
const START_ADD_ENTRY_PROCESS   = "START_ADD_ENTRY_PROCESS";
const SHOW_ENTRY_FORM           = "SHOW_ENTRY_FORM";
const HIDE_ENTRY_FORM           = "HIDE_ENTRY_FORM";


//Job Entries
const ADD_JOB_ENTRY             = "ADD_JOB_ENTRY";
const UPDATE_JOB_ENTRY          = "UPDATE_JOB_ENTRY";
const EDIT_JOB_ENTRY            = "EDIT_JOB_ENTRY";
const REMOVE_JOB_ENTRY          = "REMOVE_JOB_ENTRY";
const CLEAR_ALERT_TEXT          = "CLEAR_ALERT_TEXT";
const CANCEL_EDIT_ENTRY         = "CANCEL_EDIT_ENTRY";

//File Generate
const FILE_GENERATION_STARTED   = "FILE_GENERATION_STARTED";
const FILE_GENERATION_ENDED     = "FILE_GENERATION_ENDED";
const FILE_GENERATION_SUCCESS   = "FILE_GENERATION_SUCCESS";
const FILE_GENERATION_FAILED    = "FILE_GENERATION_FAILED";
const FILE_GENERATION_VALIDATION_FAILED = "FILE_GENERATION_VALIDATION_FAILED"
export {
        END_ADD_ENTRY_PROCESS, 
        START_ADD_ENTRY_PROCESS,
        ADD_JOB_ENTRY,
        CANCEL_EDIT_ENTRY,
        UPDATE_JOB_ENTRY,
        EDIT_JOB_ENTRY,
        REMOVE_JOB_ENTRY,
        SHOW_ENTRY_FORM,
        HIDE_ENTRY_FORM,
        CLEAR_ALERT_TEXT,
        FILE_GENERATION_STARTED,
        FILE_GENERATION_ENDED,
        FILE_GENERATION_SUCCESS,
        FILE_GENERATION_FAILED,
        FILE_GENERATION_VALIDATION_FAILED
}