//Entry Form
const REGISTRATION_PROCESS_STARTED      = "REGISTRATION_PROCESS_STARTED";
const REGISTRATION_PROCESS_ENDED        = "REGISTRATION_PROCESS_ENDED";
const REGISTRATION_VALIDATION_FAILED    = "REGISTRATION_VALIDATION_FAILED";
const REGISTRATION_SUCCESS              = "REGISTRATION_SUCCESS";
const REGISTRATION_FAILED               = "REGISTRATION_FAILED"
const REGISTRATION_TYPE                 = "REGISTRATION_TYPE";
const CLEAR_REGISTRATON_ALERTS          = "CLEAR_REGISTRATON_ALERTS";

//Auth
const UPDATE_AUTH = 'UPDATE_AUTH';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_PROCESS_STARTED = 'USER_LOGIN_PROCESS_STARTED';
const USER_LOGIN_PROCESS_ENDED = 'USER_LOGIN_PROCESS_ENDED';
const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
const USER_LOGIN_NOTIFICATION = 'USER_LOGIN_NOTIFICATION';
const CLEAR_LOGIN_NOTIFICATION = 'CLEAR_LOGIN_NOTIFICATION';
const CLEAR_LOGIN_WARNING = 'CLEAR_LOGIN_WARNING';

//Profile
const START_PROFILE_UPDATE = 'START_PROFILE_UPDATE';
const END_PROFILE_UPDATE = 'END_PROFILE_UPDATE';
const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';


export {
        REGISTRATION_PROCESS_STARTED,
        REGISTRATION_VALIDATION_FAILED, 
        REGISTRATION_PROCESS_ENDED, 
        REGISTRATION_SUCCESS, 
        REGISTRATION_FAILED, CLEAR_REGISTRATON_ALERTS,
        REGISTRATION_TYPE, 
        USER_LOGOUT,USER_LOGIN_SUCCESS, USER_LOGIN_FAILED, USER_LOGIN_PROCESS_ENDED, USER_LOGIN_PROCESS_STARTED,
        USER_LOGIN_NOTIFICATION, CLEAR_LOGIN_WARNING, CLEAR_LOGIN_NOTIFICATION, UPDATE_AUTH,
        START_PROFILE_UPDATE, END_PROFILE_UPDATE, PROFILE_UPDATE_SUCCESS, PROFILE_UPDATE_FAILED
}